=== victornguyen195/m2-case-study/app/code/Amasty/ThankYouPage/etc/block_types.xsd
<?xml version="1.0" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="block_types" type="typesList"/>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="uniqueBlockId">
            <xs:annotation>
                <xs:documentation>
                    Attribute id is unique under all fields for each group
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="block"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="typesList">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="block" type="blockItem"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="blockItem">
        <xs:sequence>
            <xs:element name="title"/>
            <xs:element name="class_name"/>
            <xs:element name="template" minOccurs="0"/>
        </xs:sequence>

        <xs:attributeGroup ref="blockAttributeGroup"/>
    </xs:complexType>

    <xs:attributeGroup name="blockAttributeGroup">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:attributeGroup>
</xs:schema>

=== victornguyen195/m2-case-study/app/code/Amasty/ThankYouPage/etc/block_types.xml
<?xml version="1.0" ?>
<!--
  @author Amasty Team
  @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
  @package Amasty_ThankYouPage

  This configuration creates ability to define more block in extensions outside of the current one
  -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="block_types.xsd">
    <block_types>
        <block id="header">
            <title>Header</title>
            <class_name>\Amasty\ThankYouPage\Block\Onepage\Success\Types\Custom\Header</class_name>
            <template>Amasty_ThankYouPage::onepage/success/types/custom.phtml</template>
        </block>

        <block id="order_review">
            <title>Order Review</title>
            <class_name>\Amasty\ThankYouPage\Block\Onepage\Success\Types\OrderReview</class_name>
            <template>Amasty_ThankYouPage::onepage/success/types/order_review.phtml</template>
        </block>

        <block id="custom1">
            <title>Custom 1</title>
            <class_name>\Amasty\ThankYouPage\Block\Onepage\Success\Types\Custom\Custom1</class_name>
            <template>Amasty_ThankYouPage::onepage/success/types/custom.phtml</template>
        </block>

        <block id="custom2">
            <title>Custom 2</title>
            <class_name>\Amasty\ThankYouPage\Block\Onepage\Success\Types\Custom\Custom2</class_name>
            <template>Amasty_ThankYouPage::onepage/success/types/custom.phtml</template>
        </block>

        <block id="custom3">
            <title>Custom 3</title>
            <class_name>\Amasty\ThankYouPage\Block\Onepage\Success\Types\Custom\Custom3</class_name>
            <template>Amasty_ThankYouPage::onepage/success/types/custom.phtml</template>
        </block>

        <block id="newsletter">
            <title>Newsletter</title>
            <class_name>\Amasty\ThankYouPage\Block\Onepage\Success\Types\Newsletter</class_name>
            <template>Amasty_ThankYouPage::onepage/success/types/newsletter.phtml</template>
        </block>

        <block id="cross_sell">
            <title>Cross-Sell</title>
            <class_name>\Amasty\ThankYouPage\Block\Onepage\Success\Types\Crosssell</class_name>
            <template>Amasty_ThankYouPage::onepage/success/types/crosssell.phtml</template>
        </block>

        <block id="create_account">
            <title>Create Account</title>
            <class_name>\Amasty\ThankYouPage\Block\Onepage\Success\Types\CreateAccount</class_name>
            <template>Amasty_ThankYouPage::onepage/success/types/create_account.phtml</template>
        </block>
    </block_types>
</config>
